name: cloudinary_url_gen
description: Cloudinary is a cloud service that offers a solution to a web application's entire image management pipeline
version: 2.0.0
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_dart

environment:
  sdk: '>=2.17.5 <4.0.0'

dependencies:
  crypto: ^3.0.3
  convert: ^3.1.1
  universal_io: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5

