name: cloudinary_api
description: Cloudinary is a cloud service that offers a solution to a web application's entire image management pipeline
version: 2.0.0
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_dart

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  http: ^1.1.0
  async: ^2.11.0
  crypto: ^3.0.3
  convert: ^3.1.1
  http_parser: ^4.0.2
  cloudinary_url_gen:
    git:
      url: https://github.com/mr7ssam/cloudinary_dart.git
      path: url_gen

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0


assets:
  - assets/sample.jpeg

